Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,7 @@ jobs:
     env:
       APP_NAME: Glimpse
       TEST_NAME: Glimpse
+      ORG_NAME: glimpseio 
     
     steps:
       - name: Checkout
@@ -25,6 +26,9 @@ jobs:
           submodules: true
           token: ${{ secrets.ACCESS_TOKEN }}
 
+      - name: Set steps.vars.outputs.tag to current release
+        id: vars
+        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
 
       - name: "Create exportOptions.plist"
         run: |
@@ -137,30 +141,36 @@ jobs:
           name: ${{ env.APP_NAME }}.zip
           path: Export/${{ env.APP_NAME }}.zip
 
-      #- name: Test
-      #  run: |
-      #    xcodebuild -scheme "Glimpse" test CODE_SIGNING_ALLOWED=NO \
-      #      -skip-testing:GlimpseTests/GlimpseTests/testLoadSampleGlimpses \
-      #      -skip-testing:GlanceTests/VegaLiteTests/testCompleteSamples \
-      #      -skip-testing:GlanceTests/VegaLiteTests/testExampleSamples \
-      #      -skip-testing:GlanceTests/VegaLiteTests/testDateTemporalFormats \
-      #      -skip-testing:VegaLiteTests/testSimpleSample \
-      #      || echo "TOLERATING TEST FAILURES FOR NOW"
+      - name: Test
+        run: |
+          xcodebuild -scheme "Glimpse" test CODE_SIGNING_ALLOWED=NO \
+            -skip-testing:GlimpseTests/GlimpseTests/testLoadSampleGlimpses \
+            -skip-testing:GlanceTests/VegaLiteTests/testCompleteSamples \
+            -skip-testing:GlanceTests/VegaLiteTests/testExampleSamples \
+            -skip-testing:GlanceTests/VegaLiteTests/testDateTemporalFormats \
+            -skip-testing:VegaLiteTests/testSimpleSample \
+            || echo "TOLERATING TEST FAILURES FOR NOW"
 
-      #- name: Upload Test Logs
-      #  uses: actions/upload-artifact@v2
-      #  with:
-      #    name: Logs.zip
-      #    path: ~/Library/Developer/Xcode/DerivedData/GIO-*/Logs/
+      - name: Upload Test Logs
+        uses: actions/upload-artifact@v2
+        with:
+          name: Logs.zip
+          path: ~/Library/Developer/Xcode/DerivedData/GIO-*/Logs/
 
-      #- name: Release
-      #  uses: softprops/action-gh-release@v1
-      #  if: startsWith(github.ref, 'refs/tags/')
-      #  with:
-      #    body_path: RELEASE_NOTES.md
-      #    files: |
-      #      CHANGELOG.md
-      #      RELEASE_NOTES.md
-      #      ${{ env.APP_NAME }}.zip
-      #  env:
-      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Generate AppCast.xml
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          RELEASE_TAG=`git tag --sort=taggerdate | tail -n 1`
+          echo '<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"><channel><item><enclosure sparkle:version="${{ steps.vars.outputs.tag }}" url="https://github.com/${{ env.ORG_NAME }}/${{ env.APP_NAME }}/releases/download/${{ steps.vars.outputs.tag }}/${{ env.APP_NAME }}.zip"></item></channel></rss>' > appcast.xml
+          
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          body_path: RELEASE_NOTES.md
+          files: |
+            CHANGELOG.md
+            RELEASE_NOTES.md
+            ${{ env.APP_NAME }}.zip
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
